services:
- hash: 6fa6a7234b311a247c40602126b31c8254a3cdc3
  name: prometheus-telemeter
  path: /manifests/prometheus/list.yaml
  url: https://github.com/openshift/telemeter
  hash_length: 7
  environments:
  - name: production
    parameters:
      NAMESPACE: telemeter-production
      PROMETHEUS_IMAGE_TAG: v2.3.2
      PROMETHEUS_CPU_REQUEST: 100m
      PROMETHEUS_CPU_LIMIT: 1
      PROMETHEUS_MEMORY_REQUEST: 500Mi
      PROMETHEUS_MEMORY_LIMIT: 8Gi
  - name: staging
    parameters:
      NAMESPACE: telemeter-stage
      PROMETHEUS_IMAGE_TAG: v2.3.2
      PROMETHEUS_CPU_REQUEST: 100m
      PROMETHEUS_CPU_LIMIT: 1
      PROMETHEUS_MEMORY_REQUEST: 500Mi
      PROMETHEUS_MEMORY_LIMIT: 8Gi
