services:
- hash: d596325caa88d4aa948a331e9531adcb484df54a
  name: prometheus-telemeter
  path: /manifests/prometheus/list.yaml
  url: https://github.com/openshift/telemeter
  hash_length: 7
  environments:
  - name: production
    parameters:
      NAMESPACE: telemeter-production
      IMAGE_TAG: v2.3.2
