services:
- hash: f833ec8d03a8670e429fcd3919f8e82fc817d176
  name: prometheus-telemeter
  path: /manifests/prometheus/list.yaml
  url: https://github.com/openshift/telemeter
  hash_length: 7
  environments:
  - name: production
    parameters:
      NAMESPACE: telemeter-production
      PROMETHEUS_IMAGE_TAG: v2.3.2
  - name: staging
    parameters:
      NAMESPACE: telemeter-stage
      PROMETHEUS_IMAGE_TAG: v2.3.2
